# Generated by Django 4.2.3 on 2023-07-20 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("multipleimagesapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gallery",
            old_name="image",
            new_name="images",
        ),
    ]
